package cn.boommanpro.sxu.crawler.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table jxl_room
 *
 * @mbg.generated do_not_delete_during_merge
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
public class JxlRoom {

    private Integer id;



    private String jxlValue;

    private String name;


    private String value;


    private LocalDateTime createDate;


    private Integer disabled;


    private Integer deleted;


    private Integer updated;


    private Integer updateTimes;


    private LocalDateTime updateDate;

    public JxlRoom(String jxlValue, String name, String value) {
        this.jxlValue = jxlValue;
        this.name = name;
        this.value = value;
    }
}